### PR TITLE
FIDO U2F High-level API

### PR DESCRIPTION
**Pull request by hultqvist**
http://fidoalliance.org/specs/fido-u2f-javascript-api-v1.0-rd-20141008.pdf

### CODE REVIEW

**Comment by danelkhen** [comment]
That's cool! 

But wouldn't it be better to put it in a separate assembly?

**Comment by hultqvist** [comment]
U2F has a way to go to be available in all browsers, people [push for it to be in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1065729) as well but so far not much is happening there.

One reason to not make it a separate assembly is that it is not really an assembly library but an API into the browser. I linked to a chrome extension previously but that is only intended as a temporary workaround, later the API will work without any extra code added to a page.

Specifically the `HtmlContect.window.u2f` is hard to add in a separate assembly.

I could change it to be `U2F.window.u2f` in a separate assembly, but it doesn't look as good and won't be as discoverable. What do you think?

**Comment by Arakis** [comment]
In my opinion, we should wait until it's official in the w3c specification, and integrated in firefox, too.

**Comment by danelkhen** [comment]
Well if it's planned to go into w3c I don't see the hard in adding it now. But if we're not sure or the API will change, perhaps it will be safer to add it as a separate assembly, but also not critical.

**Comment by hultqvist** [comment]
Feel free to do as you choose, when it is final in chrome and implemented in Firefox i can push this again.

**Pull request closed without merging**
